name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v2
    with:
      # disable auto detection of JS tests (remove if any JS tests are added)
      js: false
